// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'


    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 import 'firebase_options.dart';
/// // ...
 Future<void> main() async {
   await Firebase.initializeApp(
     options: DefaultFirebaseOptions.currentPlatform,
   );
 }
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs8MqDDlZGrtFN1szF3e7f8aRf4Y1VSN8',
    appId: '1:681138977951:web:d73c35b4febb0914d6b6aa',
    messagingSenderId: '681138977951',
    projectId: 'apecia-70303',
    authDomain: 'apecia-70303.firebaseapp.com',
    storageBucket: 'apecia-70303.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmmrg8wGYc1Sr-loa3C327fqjIib2pOa0',
    appId: '1:681138977951:android:e15fedae089b403dd6b6aa',
    messagingSenderId: '681138977951',
    projectId: 'apecia-70303',
    storageBucket: 'apecia-70303.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs8MqDDlZGrtFN1szF3e7f8aRf4Y1VSN8',
    appId: '1:681138977951:web:849523734f3734d5d6b6aa',
    messagingSenderId: '681138977951',
    projectId: 'apecia-70303',
    authDomain: 'apecia-70303.firebaseapp.com',
    storageBucket: 'apecia-70303.firebasestorage.app',
  );
}
