// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTIGRKcdcosGKeH6fnLnLWYbzc1FiTUow',
    appId: '1:329927926839:web:729a7e7cb6b4d333ec8bb2',
    messagingSenderId: '329927926839',
    projectId: 'aphasia-1b459',
    authDomain: 'aphasia-1b459.firebaseapp.com',
    storageBucket: 'aphasia-1b459.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCZGZld33uOxN1RKSwZBaBsRRCPkb2_J0',
    appId: '1:329927926839:android:2ead1ee2a1cc2fbbec8bb2',
    messagingSenderId: '329927926839',
    projectId: 'aphasia-1b459',
    storageBucket: 'aphasia-1b459.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkSqP1mZApE63QN2etgpijfaYSzOBHFUg',
    appId: '1:329927926839:ios:7792e8a1dda59f96ec8bb2',
    messagingSenderId: '329927926839',
    projectId: 'aphasia-1b459',
    storageBucket: 'aphasia-1b459.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkSqP1mZApE63QN2etgpijfaYSzOBHFUg',
    appId: '1:329927926839:ios:7792e8a1dda59f96ec8bb2',
    messagingSenderId: '329927926839',
    projectId: 'aphasia-1b459',
    storageBucket: 'aphasia-1b459.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTIGRKcdcosGKeH6fnLnLWYbzc1FiTUow',
    appId: '1:329927926839:web:7aab66e31b9d8afdec8bb2',
    messagingSenderId: '329927926839',
    projectId: 'aphasia-1b459',
    authDomain: 'aphasia-1b459.firebaseapp.com',
    storageBucket: 'aphasia-1b459.firebasestorage.app',
  );
}
